# this config file contains all config fields with comments
kind: Cluster
apiVersion: kind.sigs.k8s.io/v1alpha3
# patch the generated kubeadm config with some extra settings
kubeadmConfigPatches:
- |
  apiVersion: kubeadm.k8s.io/v1beta2
  kind: ClusterConfiguration
  metadata:
    name: config
  networking:
    serviceSubnet: 10.0.0.0/16

# # patch it further using a JSON 6902 patch
# kubeadmConfigPatchesJson6902:
# - group: kubeadm.k8s.io
#   version: v1beta2
#   kind: ClusterConfiguration
#   patch: |
#     - op: add
#       path: /apiServer/certSANs/-
#       value: my-hostname

# 1 control plane node and 3 workers
nodes:
# the control plane node config
- role: control-plane
  extraPortMappings:
  - containerPort: 30080
    hostPort: 30080
  - containerPort: 30081
    hostPort: 30081
  - containerPort: 30082
    hostPort: 30082
  - containerPort: 30083
    hostPort: 30083
  - containerPort: 30084
    hostPort: 30084
  - containerPort: 30085
    hostPort: 30085
#  extraMounts:
#  - containerPath: /mounts
#    hostPath: /var/lib/kind/mounts

# the three workers
- role: worker
- role: worker
- role: worker
